# Generated by Django 3.0.4 on 2020-03-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='photograph',
            field=models.ImageField(default='student/images/default.png', null=True, upload_to='student/images'),
        ),
    ]
