# Generated by Django 3.0.4 on 2020-03-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studentsubject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubject',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.AllSemester'),
        ),
        migrations.DeleteModel(
            name='StudentSemester',
        ),
    ]
